# Generated by Django 3.2.15 on 2022-10-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20221026_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='hero_image',
            new_name='thumbnail_image',
        ),
    ]
